# Use an official Python runtime as the base image
FROM python:3.8-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the "main.py" file to the container
COPY main.py .

# Run the command to execute the "main.py" file
CMD ["python", "./main.py"]

